repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'
    hooks:
    -   id: mypy
        args: [--strict, --ignore-missing-imports, --explicit-package-bases]
        additional_dependencies: [tokenize-rt==3.2.0]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: 'v1.10.0'
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal
    -   id: text-unicode-replacement-char
-   repo: https://github.com/pre-commit/sync-pre-commit-deps
    rev: v0.0.1
    hooks:
    -   id: sync-pre-commit-deps
-   repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
    -   id: bandit
        exclude: ^tests/
-   repo: https://github.com/PyCQA/pydocstyle
    rev: '6.3.0'
    hooks:
    -   id: pydocstyle
-   repo: https://github.com/PyCQA/pylint
    rev: 'v2.17.6'
    hooks:
    -   id: pylint
-   repo: https://github.com/PyCQA/doc8
    rev: 'v1.1.1'
    hooks:
    -   id: doc8
-   repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
    -   id: isort
-   repo: https://github.com/PyCQA/docformatter
    rev: 'v1.7.5'
    hooks:
    -   id: docformatter
-   repo: https://github.com/PyCQA/autoflake
    rev: 'v2.2.1'
    hooks:
    -   id: autoflake
