[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "AmplifyP"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib",
]

[project.optional-dependencies]
tests = [
  'pytest',
]
